print ("Mad Libs Pro")
print ("By Sean Walla Walla")
print ("Version 1.0 September 10th 2018 to September 12th 2018")
print (" ")
print ("Catalogs")
print (" ")
print ("Copy-Pastas")
print (" ")
print ("High IQ | ID = 3333")
print (" ")
print ("School")
print (" ")
print ("Computer lab software | ID = 2414")
print (" ")
print ("Food")
print (" ")
print (" ")
print (" ")
print ("Jobs")
print (" ")
print (" ")
print (" ")
print ("Tongue Twisters 0~~~~ ")
print (" ")
print ("Seashore | ID = 4693")
print ("Witch    | ID = 6006")

input1 = int(input("Type in an ID to begin:"))
if input1 == 2414:
	print (" ")
	print ("Computer lab software ")
	print (" ")
	word1 = input("Our computer lab is ")
	word2 = input("We use this ")
	word3 = input("Software called ")
	word4 = input("It really")
	word5 = input("Us ")
	word6 = input("Really ")
	word7 = input("I ")
	word8 = input("Our computer lab, it really helps me ")
	print ("Results")
	print (" ")
	print ("Our computer lab is " + word1 + " We use this " + word2 + " Software called " + word3 + " It really " + word4 + " us " + word5 + " Really " + word6 + " I " + word7 + "Our computer lab. It really helps me " + word8 + " ")
	print (" ")
	print ("Did you like that?")
if input1 == 3333:
	print (" ")
	print ("Make your own Rick and Morty copy-pasta")
	print (" ")
	word1 = input("To be fair, you have to have a very high IQ to understand ")
	word2 = input("The humor is extremely subtle, and without a solid grasp of ")
	word3 = input("most of the jokes will go over a typical viewer's head. There's also ")
	word4 = input("which is deftly woven into his characterisation - his personal")
	word5 = input("draws heavily from")
	word6 = input("literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the")
	word7 = input("of these jokes")
	word8 = input("to realize that they're not just funny- they say something deep about")
	word9 = input("As a consequence people who dislike")
	word10 = input("truly ARE")
	word11 = input("of course they wouldn't appreciate, for instance, the humour in")
	word12 = input("existencial catchphrase")
	word13 = input("which itself is a cryptic reference to")
	word14 = input("I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as")
	word15 = input("genius unfolds itself on their")
	word16 = input("What fools... how I pity them. And yes by the way, I DO have a")
	word17 = input("tattoo. And no, you cannot see it. It's for the ladies' eyes only And even they have to demonstrate that they're within")
	word18 = input("IQ points of my own (preferably lower) beforehand.")
	print (" ")
	print ("Results")
	print (" ")
	print ("To be fair, you have to have a very high IQ to understand " + word1 + " The humor is extremely subtle, and without a solid grasp of " + word2 + " most of the jokes will go over a typical viewer's head. There's also " + word3 + " which is deftly woven into his characterisation - his personal " + word4 + " draws heavily from " + word5 + " literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the " + word6 + " of these jokes " + word7 + " to realize that they're not just funny- they say something deep about" + word8)
	print (" As a consequence people who dislike " + word9 + " truly ARE " + word10 + " of course they wouldn't appreciate, for instance, the humour in" + word11 + " existencial catchphrase " + word12 + " which itself is a cryptic reference to" + word13 + " I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as " + word14 + " genius unfolds itself on their " + word15 + " What fools... how I pity them. And yes by the way, I DO have a " + word16)
	print (" tattoo. And no, you cannot see it. It's for the ladies' eyes only- And even they have to demonstrate that they're within " + word17 + " IQ points of my own (preferably lower) beforehand. " + word18 + " ")
	print ("Did you like that?")
if input1 == 4693:
	print (" ")
	print ("Seashore")
	print ("Example:")
	print ("'Sally Collected Seashells at the seashore'")
	word1 = input(" ")
	word2 = input ("Collected ")
	word3 = input ("At the")
	print (" ")
	print ("Results")
	print (" ")
	print (word1 + " Collected " + word2 + " at the" + word3)
	print ("Did you like that?")
if input1 == 6006:
	print ("Witch")
inputfinal = input("Press [ENTER] key to quit:")
if inputfinal == ("H"):
	print ("Goodbye")
else:
	print ("GDBY") 