print ("R E A C T O P")
print (" ")
print (" ")
import time
while True:
    print("Press any key within 5 seconds to enter the BIOS")
    time.sleep(5) # Delay for 1 minute (5 seconds)
import os
os.system('clear')
print ("Reactop Bootloader")
print (" ")
print ("Boot from:")
print ("1 Windows 3.1")
print ("2 Windows 98 Second Edition")
print ("3 Windows XP SP3")
print ("4 ReactOS 0.5")
print ("5 ReactOS main")
print ("6 Custom slot 1")
print ("7 Custom slot 2")
print ("8 Custom slot 3")
inp = int(input("9 Custom slot 4")
if inp = 1
	print ("Booting from system 1: Windows 3.11")
	print ("Processing, please wait...")
if inp = 2
	print ("Booting from system 2: Windows 98 SE")
	print ("Processing, please wait...")
if inp = 3
	print ("Booting from system 3: Windows XP professional Service Pack 3")
	print ("Processing, please wait...")
if inp = 4
	print ("Booting from system 4: ReactOS beta 0.5")
	print ("Processing, please wait...")
if inp = 5
	print ("Booting from system 5: Main ReactOS port")
	print ("Processing, please wait...")
if inp = 6 
	print ("Booting from custom slot 1")
	print ("Processing, please wait...")
if inp = 7 
	print ("Booting from custom slot 2")
	print ("Processing, please wait...")
if inp = 8 
	print ("Booting from custom slot 3")
	print ("Processing, please wait...")
if inp = 9
	print ("Booting from custom slot 4")
	print ("Processing, please wait...")
else:
	print ("R E A C T O P _ O P E N _ B I O S")
	print ("Version 1.4")
	print ("System 1 settings")
	print ("Memory (RAM): 8 Megabytes ^v")
	print ("System 2 settings")
	print ("Memory (RAM): 128 Megabytes ^v")
	print ("System 3 settings")
	print ("Memory (RAM): 1024 Megabytes ^v")
	print ("System 4 settings")
	print ("Memory (RAM): 4096 Megabytes ^v")
	print ("System 5 settings")
	print ("Memory (RAM): 8192 Megabytes ^v")
	print ("System 6 settings")
	print ("Memory (RAM): 100 Megabytes ^v")
	print ("System 7 settings")
	print ("Memory (RAM): 100 Megabytes ^v")
	print ("System 8 settings")
	print ("Memory (RAM): 100 Megabytes ^v")
	print ("System 9 settings")
	print ("Memory (RAM): 100 Megabytes ^v")
	print ("Boot type")
	print ("IDE")
	print ("UEFI")
	print ("CDE")
	print ("SATA")
	print ("System Birthday: Unset")
	print ("System storage: 500 Gigabytes B2 = 440 Gigabytes")